### ISSUE TITLE
Back button

### ISSUE THREAD

**Issue by kanishka-parmar** [surajondev/UI-UX-Design#120]
Most of the designs lack the back button like image-slider, cards, forms, etc.
I would like to add the back button on every design page . 
This will make the site user friendly.
@surajondev Please assign this to me i want to work under HactoberFest 2023.

**Comment by surajondev** [comment]
This is a good idea. You can work on it.

**Comment by kanishka-parmar** [comment]
Should I add complete navigation bar or just a back button?

**Comment by surajondev** [comment]
Whatever suits best. I think navigation bar would be better.

**Comment by kanishka-parmar** [comment]
Ok I will work on navigation bar.
