### ISSUE TITLE
Hover effect is affecting other cards in the hero section.

### ISSUE THREAD

**Issue by nirmalyax** [surajondev/UI-UX-Design#123]
<img width="1440" alt="Screenshot 2023-10-21 at 11 28 44 PM" src="https://github.com/surajondev/UI-UX-Design/assets/35608135/8cfa5399-3a42-4531-a873-7a51a78222b2">
The hover effect is changing the padding of the other cards. 
need to look into it.

**Comment by surajondev** [comment]
You can work on this.

**Comment by nirmalyax** [comment]
The issue is fixed.
