### ISSUE TITLE
Rework of the main page UI

### ISSUE THREAD

**Issue by xMrAfonso** [surajondev/UI-UX-Design#30]
Hi, I would like to redo the whole main page of the website to a more modern design. If possible assign me this issue.

Here is the design I plan on doing (made in Figma):
![Prototype #1](https://user-images.githubusercontent.com/44532605/194750324-9eb1e733-32b2-48af-8c87-77df9bdd804f.png)
I went with a more simplistic approach and did a simple logo for the website. I still include some purple since that was one of the main colors here but otherwise, I am going with some shades of white and gray.

**Comment by xMrAfonso** [comment]
Regarding this, already started working on it, will push a PR whenever it's ready.

**Comment by surajondev** [comment]
The design looks awesome. Thanks for working on it.

**Comment by xMrAfonso** [comment]
> The design looks awesome. Thanks for working on it.

Thanks, regarding when it comes to submitting the PR. Should I create a folder named "Index-MrAfonso" or should I change directly the index.html? The contribution file doesn't really specify this.

**Comment by surajondev** [comment]
Make change directly into the index.html

**Comment by xMrAfonso** [comment]
Just posted the PR: #31

**Comment by surajondev** [comment]
Thanks. It has been merged.
