### ISSUE TITLE
Testimonial UI

### ISSUE THREAD

**Issue by surajondev** [surajondev/UI-UX-Design#4]
Create a testimonial UI that contains
- Rating
- Review
- Profile Pic of Reviewer with name

**Comment by Pandademic** [comment]
@surajondev I would love to contribute and do this one!

**Comment by surajondev** [comment]
> may contribute to it? if yes then assign it to me kindly

Sure. Just name the directory with "Testimonial" followed by your name.

**Comment by ShahrozAhmd** [comment]
hey, sorry for that, but I already have contributes to the navbar issue of this repo, you can check it now I prefer to contribute to other reports of yours, so for that reason, I reassign myself for this issue, may be later I also contribute more in this particular repo, hope you can understand.

**Comment by surajondev** [comment]
Okay.
