### ISSUE TITLE
Responsive Cards and Navigation bar using Chakra-UI and NextJs.

### ISSUE THREAD

**Issue by KmKalpana** [surajondev/UI-UX-Design#42]
Hii @surajondev , can I make a responsive cards and navigation bar using Chakra-UI and Nextjs.

**Comment by xMrAfonso** [comment]
Wow seems quite a bit too much for a HTML, CSS (& JS) focused project in my opinion... maybe not the right project.

This project is meant to help beginners, pretty sure no beginner will start with Nextjs xD. Think it goes against the point of the project, but we will see what surajondev says.

**Comment by KmKalpana** [comment]
I am familiar with HTML, CSS and JS. If you have any idea regarding project you can suggest me . Either I can make the responsive cards in html,css and javascript.

**Comment by xMrAfonso** [comment]
Think the only issue is the use of advanced tools like Nextjs, if you are able to do that with html, css and js, would be prefered for new coders probably.

> I am familiar with HTML, CSS and JS. If you have any idea regarding project you can suggest me . Either I can make the responsive cards in html,css and javascript.

**Comment by KmKalpana** [comment]
Okay

**Comment by KmKalpana** [comment]
Okay
