### ISSUE TITLE
Making go back button in alert section working and it will take us to home page.

### ISSUE THREAD

**Issue by kumarsanu2002** [surajondev/UI-UX-Design#46]
@surajondev  pls assign it to me and letter on I will add more section .

**Comment by xMrAfonso** [comment]
Not the only one with issues, the Cards go back also doesn't work, if you are able to fix it, would be cool. I tried fixing it myself but I am quite a mess with links xD

**Comment by kumarsanu2002** [comment]
@xMrAfonso I will be happy to help.
