### ISSUE TITLE
Add Search Bar

### ISSUE THREAD

**Issue by neerajbelsare** [surajondev/UI-UX-Design#77]
I can add an animated responsive search bar. Can you please assign me?

**Comment by xMrAfonso** [comment]
Sure, if you make it in the main page, make sure to follow the theme, otherwise create a separate page for it.

**Comment by neerajbelsare** [comment]
Yeah, I could do both. I will try to include it in the main page itself.

**Comment by santhos-13** [comment]
@xMrAfonso i can solve this issue can you assign it to me
