### ISSUE TITLE
Improve UI design in 'Select User'

### ISSUE THREAD

**Issue by TrlRizu** [surajondev/UI-UX-Design#97]
I find that this page needs a bit of a makeover. May I work on it? (I'll keep the colour scheme of the page, if preferred)

**Comment by TrlRizu** [comment]
I've opened a pull request for it. Hope you can check it out! https://github.com/surajondev/UI-UX-Design/pull/98

**Comment by surajondev** [comment]
Thanks it has been merged.

**Comment by TrlRizu** [comment]
Thanks so much!
